### ISSUE TITLE
Compilation errors with mingw 5.3.0

### ISSUE THREAD

**Issue by KiBorg0** [TinyTinni/ValveFileVDF#1]
C:\Programming\untitled1\vdf_parser.hpp:336: ошибка: redeclaration of 'template<class iStreamT, class charT> tyti::vdf::basic_object<charT> tyti::vdf::read(iStreamT&, bool*)' may not have default arguments [-fpermissive]
         basic_object<charT> read(iStreamT& inStream, bool *ok = 0)
                                                                  ^
C:\Programming\untitled1\main.cpp:15: ошибка: no matching function for call to 'read(std::ifstream&)'
     auto root = vdf::read(file);
                               ^
c:\mingw\lib\gcc\mingw32\5.3.0\include\c++\bits\stl_pair.h:102: ошибка: 'std::pair<_T1, _T2>::second' has incomplete type
       _T2 second;                /// @c second is a copy of the second object
           ^

**Comment by KiBorg0** [comment]
If use http://stackoverflow.com/questions/32105975/why-cant-i-have-template-and-default-arguments
then first error disappears

**Comment by TinyTinni** [comment]
Hi,
I will test it with MinGW when i have time (still working with VS2015).

Default template paremeter should be [added with c++11.](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#226)
Therefore, mandatory question, did you activated the c++11 switch (-std=c++11) (guess its enabed by default with gcc 6.0).
Since you use auto, i guess you use it already.

Maybe there is something wrong with the deduction.
The second template parameter is based on the first one and the resulting type is constructed using the second parameter.
Does it work, when you help the compiler?
Try using:
`auto root = vdf::read<std::ifstream,char>(file)`
or 
`auto root = vdf::read<std::ifstream>(file)`
(ofc. only, if `file` is an object of type `std::ifstream`)

**Comment by KiBorg0** [comment]
Thanks for answer, yes I activated c++11 with QMAKE_CXXFLAGS += -std=c++11 in project configuration and it works fine. I also tryed your suggestions, but nothing has changed, the same errors.
And, if I move default arguments for template and function from defenition to declararion, like this:
Declaration
`        template<typename iStreamT, typename charT = typename iStreamT::char_type>
        basic_object<charT> read(iStreamT& inStream, bool *ok = 0);`
Defenition
`        template<typename iStreamT, typename charT>
        basic_object<charT> read(iStreamT& inStream, bool *ok)`
I have only one error:
C:\Programming\untitled1\vdf_parser.hpp:287: required from 'struct tyti::vdf::basic_object<char>'
C:\Programming\untitled1\main.cpp:15: required from here
c:\mingw\lib\gcc\mingw32\5.3.0\include\c++\bits\stl_pair.h:102: error: 'std::pair<_T1, _T2>::second' has incomplete type
       _T2 second;                /// @c second is a copy of the second object
           ^

**Comment by KiBorg0** [comment]
In this construction:
`1        template<typename CharT>`
`2        struct basic_object`
`3        {`
`4            typedef CharT char_type;`
`5            std::basic_string<char_type> name;`
`6            std::unordered_map<std::basic_string<char_type>, std::basic_string<char_type> > attribs;`
`7            std::unordered_map<std::basic_string<char_type>, basic_object<char_type> > childs;`
`8        };`

**Comment by TinyTinni** [comment]
Ah yes thanks,
`basic_object<charT>` is an incomplete type in this case and therefore, this is definitely wrong.

Is should be a (smart) pointer.
I will change it.

**Comment by TinyTinni** [comment]
reopening.

Forgot to ask,
does it also solve the other 2 compiler errors?

**Comment by KiBorg0** [comment]
Look at my previous posts, I fixed 2 other compilation errors in another way. Now everything is compiled without errors, thanks for quick fix.

**Comment by TinyTinni** [comment]
Default arguments are also fixed now, thanks.
